---
name: Release
on:
  workflow_run:
    workflows: ["Docker build"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  derivates:
    name: Lookup derivates
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ env.derivates }}
    steps:
      - uses: actions/checkout@v4
      - name: Lookup derivates
        run: echo "derivates=$(make _derivates)" >> "$GITHUB_ENV"
  build:
    name: HTTPS proxy
    runs-on: ubuntu-22.04
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: derivates
    strategy:
      fail-fast: false
      matrix:
        derivate: ${{ fromJSON(needs.derivates.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build HTTPS ${{ matrix.derivate }} proxy
        uses: docker/build-push-action@v6
        with:
          file: "Dockerfile"
          target: ${{ matrix.derivate }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          context: context
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.title=HTTPS ${{ matrix.derivate }} proxy
            org.opencontainers.image.description=Docker image for HTTPS ${{ matrix.derivate }} proxy
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ matrix.derivate }}-${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.derivate }}
  cleanup:
    name: Cleanup
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Delete old container packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ github.token }}
